### PR TITLE
Bug fixes and fish 2

### PR DESCRIPTION
**Pull request by LemonBreezes**
This is a redoing of the first Fish & bug fixes PR. I haven't touched the module flags and keybindings situation.

### CODE REVIEW

**Comment by LuigiPiucco** [comment]
I'd merge the first and second right now, but it occurred to me that the third isn't really Corfu dependent, it doesn't reference any Corfu symbols in it's config and could stand alone. If you want it on mainline faster, I think it's worth extracting to a separate PR targeted upstream (maybe in the fish/bash `:lang` modules? Or the `:term` category?). Please take a moment to investigate, if not I'll merge.

**Comment by LemonBreezes** [comment]
> I'd merge the first and second right now, but it occurred to me that the third isn't really Corfu dependent, it doesn't reference any Corfu symbols in it's config and could stand alone. If you want it on mainline faster, I think it's worth extracting to a separate PR targeted upstream (maybe in the fish/bash `:lang` modules? Or the `:term` category?). Please take a moment to investigate, if not I'll merge.

Ah wait a second. I'm the maintainer of `fish-completion` so I'll just add it to `global-fish-completion-mode`. 

EDIT: That won't be enough though Doom doesn't use that.

**Comment by LemonBreezes** [comment]
Most likely it will just have to wait until Doom 3.0 then I think. It doesn't really fit in anywhere but I can PR it into the Eshell module.

**Comment by LemonBreezes** [comment]
I just realized the +tng flag was removed and was made the default but `TAB` cycling was removed and also the magic RET no longer exits the minibuffer after completing. I think we should revert those changes and go back to the old style that mimics the Company module and just add a `+corfu-want-magic-RET` and `+corfu-want-magic-DEL` variable.

**Comment by LemonBreezes** [comment]
The changes were too extensive and basically broke the `+tng` behavior we had before. I'm just gonna use the previous version of the module for some time because I would personally just be reverting these changes. I think such wild drastic changes to the module's keybindings and flags should be broken up into smaller commits as well because this is very difficult for me to thoroughly review. I don't understand the reasoning for each of these individual changes either so I do not feel comfortable reverting your changes without discussing it with you first.

**Comment by LuigiPiucco** [comment]
About `DEL`, it's still there, no? I seems to work here; I select a completion and press backspace, it resets.

For the other issue, I thought you wanted `RET` to exit the minibuffer so as to not interfere when unexpected, but that having to press twice when you did want to complete was okay. If your intent is to always exit on `RET`, even on complete, that prevents from using completion more than one time, which I believe most people want to do. To my knowledge, `RET`-to-confirm is more common than `TAB`-and-go, because that's what VSCode uses (and Doom users often come from VSCode), so we'll keep that default for now.

Below is my suggestion to solve this impasse, which I'll implement shortly for you to test:
1. Add `TAB` cycling by default, since that is pretty common anyway;
2. Add a conditional `corfu-insert` call to `exit-minibuffer-hook`, but only if neither `RET` flags are enabled;
3. You can then remove the `+on-ret` and `+on-ret-pt` flags if they're present;

If my guess is correct, this should be exactly what you want. In case you do use the `+on-ret` flags along with `TAB`, what we can do instead is add a variable for deciding if the user expects to complete more than once, and condition the call to `exit-minibuffer` on that.

**Comment by LemonBreezes** [comment]
> About `DEL`, it's still there, no? I seems to work here; I select a completion and press backspace, it resets.
> 
> For the other issue, I thought you wanted `RET` to exit the minibuffer so as to not interfere when unexpected, but that having to press twice when you did want to complete was okay. If your intent is to always exit on `RET`, even on complete, that prevents from using completion more than one time, which I believe most people want to do. To my knowledge, `RET`-to-confirm is more common than `TAB`-and-go, because that's what VSCode uses (and Doom users often come from VSCode), so we'll keep that default for now.
> 
> Below is my suggestion to solve this impasse, which I'll implement shortly for you to test:
> 
>     1. Add `TAB` cycling by default, since that is pretty common anyway;
> 
>     2. Add a conditional `corfu-insert` call to `exit-minibuffer-hook`, but only if neither `RET` flags are enabled;
> 
>     3. You can then remove the `+on-ret` and `+on-ret-pt` flags if they're present;
> 
> 
> If my guess is correct, this should be exactly what you want. In case you do use the `+on-ret` flags along with `TAB`, what we can do instead is add a variable for deciding if the user expects to complete more than once, and condition the call to `exit-minibuffer` on that.

That sounds good. Also, I like not having to press RET twice in the minibuffer because the candidate is already inserted anyways with the preview when you cycle candidates. RET is still useful separately for `corfu-insert` when you are using `yasnippet-capf` and `cape-abbrev`, though nobody uses those in the minibuffer so saving a RET press is better.

**Comment by LemonBreezes** [comment]
So we always need RET bound to `corfu-insert` in normal buffers because of snippets from `lsp` and `doom-snippets`. That's why I think we should just have maybe a `+magic-ret` or `passthrough-ret` flag and leave `on-ret` basically the default even without flags. A flag is too much for just a single keybinding IMO. I think `+corfu-want-magic-RET` should just be a variable and the `:filter` function should check that variable just-in-time rather than forcing the user to restart Emacs and run `doom sync`.

EDIT: Or maybe make the magic ret the default to be honest. One user already complained about having to hit RET twice in the minibuffer.

**Pull request closed without merging**
