### PR TITLE
Bug fixes and fish 2

### PR DESCRIPTION
**Pull request by LemonBreezes**
Hello. I just checked out the newest version of the module and these are some minor changes I am requesting. Please check them out. This PR will grow over the next few days if I notice anything else.

### CODE REVIEW

**Comment by LuigiPiucco** [comment]
So, because I don't use snippets that much, I will just ask you to provide some examples of how it expands after these commits. It doesn't start expanding as soon as you cycle to a snippet candidate with TAB, does it? Because in Corfu's README, there's an explicit note on not surprising the user with snippet expansions, but since I don't really use them I'm not qualified to tell. Also, early in development, I hacked together a snippet provider based on `company-yasnippet`, and because it wasn't aware of Corfu's expansion conventions, telling whether typing something with the popup open would expand or not was very hard to predict. If these remarks bear any relation to current behavior of the PR, I ask that you gate those behind a variable. If not, just clarify and I'll merge.

**Comment by LemonBreezes** [comment]
> So, because I don't use snippets that much, I will just ask you to provide some examples of how it expands after these commits. It doesn't start expanding as soon as you cycle to a snippet candidate with TAB, does it? Because in Corfu's README, there's an explicit note on not surprising the user with snippet expansions, but since I don't really use them I'm not qualified to tell. Also, early in development, I hacked together a snippet provider based on `company-yasnippet`, and because it wasn't aware of Corfu's expansion conventions, telling whether typing something with the popup open would expand or not was very hard to predict. If these remarks bear any relation to current behavior of the PR, I ask that you gate those behind a variable. If not, just clarify and I'll merge.

Okay, I just added variables controlling the smart tab behavior in Corfu.

EDIT: Part of the problem is that Doom snippets has A LOT of garbage elisp snippets.

**Comment by LemonBreezes** [comment]
> So, because I don't use snippets that much, I will just ask you to provide some examples of how it expands after these commits. It doesn't start expanding as soon as you cycle to a snippet candidate with TAB, does it? Because in Corfu's README, there's an explicit note on not surprising the user with snippet expansions, but since I don't really use them I'm not qualified to tell. Also, early in development, I hacked together a snippet provider based on `company-yasnippet`, and because it wasn't aware of Corfu's expansion conventions, telling whether typing something with the popup open would expand or not was very hard to predict. If these remarks bear any relation to current behavior of the PR, I ask that you gate those behind a variable. If not, just clarify and I'll merge.

Also, what's different about your backend for snippets? My only issue with Elken's backend is that it doesn't use `(bounds-of-thing-at-point 'word)` so it doesn't work when you call it without a prefix. Elken reverted my PR which fixed that. Though maybe the info popup could be better somehow, dunno.

**Comment by LemonBreezes** [comment]
> So, because I don't use snippets that much, I will just ask you to provide some examples of how it expands after these commits. It doesn't start expanding as soon as you cycle to a snippet candidate with TAB, does it? Because in Corfu's README, there's an explicit note on not surprising the user with snippet expansions, but since I don't really use them I'm not qualified to tell. Also, early in development, I hacked together a snippet provider based on `company-yasnippet`, and because it wasn't aware of Corfu's expansion conventions, telling whether typing something with the popup open would expand or not was very hard to predict. If these remarks bear any relation to current behavior of the PR, I ask that you gate those behind a variable. If not, just clarify and I'll merge.

Actually, Elken doesn't seem keen on making `yasnippet-capf` work without a prefix like how `company-yasnippet` does (I have the PR open). I vote to replace that package.

**Comment by LuigiPiucco** [comment]
Well, Elken's package was made specifically for this module, so I'm not very toward just replacing it. But let's take a step back and review things: what is the exact behavior you want to implement? I'm still not fully clear on that, plus it seems like there may be two separate things? An issue with prefixing and the older one with preferring expansion vs. indentation/completion. I'm sorry if it should be obvious, but I'm slightly ill these past few days and consequently somewhat slow on the uptake. You can ping me on Discord if you feel like this could benefit from faster discussion.

**Comment by LemonBreezes** [comment]
> Well, Elken's package was made specifically for this module, so I'm not very toward just replacing it. But let's take a step back and review things: what is the exact behavior you want to implement? I'm still not fully clear on that, plus it seems like there may be two separate things? An issue with prefixing and the older one with preferring expansion vs. indentation/completion. I'm sorry if it should be obvious, but I'm slightly ill these past few days and consequently somewhat slow on the uptake. You can ping me on Discord if you feel like this could benefit from faster discussion.

I ended up switching to `consult-yasnippet` for C-x C-s with `(setq consult-yasnippet-always-overwrite-thing-at-point t consult-yasnippet-use-thing-at-point t)`. It's a better fit for my use of that keybinding and addresses my issues with `yasnippet-capf`.

Also, I have updated the PR to add the fixes Hpfr requested. This PR is now ready.

**Pull request closed without merging**
