### PR TITLE
feat(corfu): add more completion-at-point-functions

### PR DESCRIPTION
**Pull request by LemonBreezes**
This PR makes some minor fixes here and there and makes the following significant changes:

1. Add more `completion-at-point-functions` for various major modes. 
2. Replace the `+corfu-completion-styles` mechanism with `+orderless-wildcard-character`, a more ergonomic way of using `corfu-separator`.
3. Enables Corfu in the minibuffer.

### CODE REVIEW

**Comment by LemonBreezes** [comment]
Okay, one more thing needs to be addressed that I just noticed. In `evil-ex-command`, after inserting a Corfu candidate, the search does not update. So that needs to be addressed or Corfu can be disabled in `evil-ex-command` instead.

**Comment by LuigiPiucco** [comment]
I've had an issue with my setup (I must use Windows now with WSL, unfortunately, and it's quite unstable), which is currently broken but I'll check everything once I fix it. Thanks in advance, though.

**Comment by LemonBreezes** [comment]
> I've had an issue with my setup (I must use Windows now with WSL, unfortunately, and it's quite unstable), which is currently broken but I'll check everything once I fix it. Thanks in advance, though.

It's OK. I just made some changes to fix up the minibuffer completion so that it works well in `evil-ex-search`, `isearch`, and the `query-replace` commands when Anzu is enabled. This feature is dependent on an Anzu PR (https://github.com/emacsorphanage/anzu/pull/125) but will not emit an error without it, the visual hint will just not be updated.

**Comment by LemonBreezes** [comment]
Also related, I made some PRs to `yasnippet-capf`: https://github.com/elken/yasnippet-capf/pull/16, https://github.com/elken/yasnippet-capf/pull/15, which significantly improve my personal experience of using this module.

But yeah, I opened the PR again because I have finished making changes for now.

**Comment by minad** [comment]
I've only looked at this briefly. FWIW my recommendation is to keep things simple at first, and refine the module iteratively in response to feedback by other users. You are certainly using the Capf transformers in a nice way and as intended, e.g., the new `cape-capf-inside-faces`, but be aware that such a level of fine tuning with lots of enabled Capfs may lead to debugging issues and performance issues. As a general rule of thumb, if you are adding large (and potentially brittle) functions, something can be improved - either the code can be upstreamed or it may not be the best idea in the first place. I mean functions like `+corfu-insert-space-maybe-quit`, `+corfu--insert-before-exit-minibuffer-a`, `+corfu--return-insert-a`, `+orderless-escapable-split-fn`, ...

**Comment by LemonBreezes** [comment]
> I've only looked at this briefly. FWIW my recommendation is to keep things simple at first, and refine the module iteratively in response to feedback by other users. You are certainly using the Capf transformers in a nice way and as intended, e.g., the new `cape-capf-inside-faces`, but be aware that such a level of fine tuning with lots of enabled Capfs may lead to debugging issues and performance issues. As a general rule of thumb, if you are adding large (and potentially brittle) functions, something can be improved - either the code can be upstreamed or it may not be the best idea in the first place. I mean functions like `+corfu-insert-space-maybe-quit`, `+corfu--insert-before-exit-minibuffer-a`, `+corfu--return-insert-a`, `+orderless-escapable-split-fn`, ...

Yeah, I was thinking about this and I remembered that I showed my idea of using comma as a Corfu separator to @pushqrdx on the Doom Emacs server and he liked it a lot so I thought @LuigiPiucco might like it too since he wanted to do fuzzy completion in Corfu, and I think this is a more ergonomic solution to that than using `C-SPC` to insert a separator. 

But definitely `+corfu--insert-before-exit-minibuffer-a`, I think should be upstreamed. That will take some time though because I'm still trying to get my company to sign the paperwork for the FSF and it really is quite a hassle. And this change involves many packages like Evil/Anzu/Isearch that will take me more time to get PRs into due to the maintenance status of each of those packages. 

Definitely adding all those CAPFs is a bit of an experiment for me. I think the choice of having strong `cape-dabbrev` completion everywhere is a good one and some like `cape-dict` I'll only use if I'm typing the name of a country or something. I don't notice any performance differences personally to be honest.

**Comment by LemonBreezes** [comment]
> I've only looked at this briefly. FWIW my recommendation is to keep things simple at first, and refine the module iteratively in response to feedback by other users. You are certainly using the Capf transformers in a nice way and as intended, e.g., the new `cape-capf-inside-faces`, but be aware that such a level of fine tuning with lots of enabled Capfs may lead to debugging issues and performance issues. As a general rule of thumb, if you are adding large (and potentially brittle) functions, something can be improved - either the code can be upstreamed or it may not be the best idea in the first place. I mean functions like `+corfu-insert-space-maybe-quit`, `+corfu--insert-before-exit-minibuffer-a`, `+corfu--return-insert-a`, `+orderless-escapable-split-fn`, ...

Yeah, I was thinking about this and I remembered that I showed my idea of using comma as a Corfu separator to @pushqrdx on the Doom Emacs server and he liked it a lot so I thought @LuigiPiucco might like it too since he wanted to do fuzzy completion in Corfu, and I think this is a more ergonomic solution to that than using `C-SPC` to insert a separator. 

But definitely `+corfu--insert-before-exit-minibuffer-a`, I think should be upstreamed. That will take some time though because I'm still trying to get my company to sign the paperwork for the FSF and it really is quite a hassle. And this change involves many packages like Evil/Anzu/Isearch that will take me more time to get PRs into due to the maintenance status of each of those packages.

**Comment by LuigiPiucco** [comment]
I think I'll be able to look at this with proper care soon, but upon a glance, the description of new features seems rather light, and the keybindings table is the same (this is not an issue in case you didn't modify any). If you want to speed things along, detail the README a bit more, so that I can better understand the modifications and intent.

**Comment by LemonBreezes** [comment]
> I think I'll be able to look at this with proper care soon, but upon a glance, the description of new features seems rather light, and the keybindings table is the same (this is not an issue in case you didn't modify any). If you want to speed things along, detail the README a bit more, so that I can better understand the modifications and intent.

Hi. So I updated the README a bit more, and updated the keybindings listed. 

Also, I added a magic `DEL` keybinding for `+tng` which resets the completion if we have a candidate selected. This is usually the intended behavior for me when I type `DEL` while completing with `+tng`.

**Comment by LemonBreezes** [comment]
Stefan Monnier showed me how to do the conditional keybindings using the built-in `menu-item` functionality:
```elisp
;; Quit completion after typing the wildcard followed by a space.
(keymap-set corfu-map "SPC"
            `(menu-item "corfu-maybe-quit" nil
              :filter
              ,(lambda (_)
                 (when (and (> (point) (point-min))
                            (eq (char-before)
                                +orderless-wildcard-character))
                   (corfu-quit)
                   nil))))
```
So I was able to refactor some hackery out !

**Comment by LuigiPiucco** [comment]
@LemonBreezes

I've checked this and it does seem quite good. I have some minor improvements/fixes and one behavior change, but I can add those after merging (I have them ready). Overall:

1. The only issue I see is that the `vertico` module already sets `orderless-component-separator` to `"[ &]"`, so the result of `+orderless-escapable-split-fn` may not be used depending on load order. In my `init.el`, `vertico` comes after `corfu`, and therefore breaks the separator (also breaks on `doom/reload`). If I understood correctly, the purpose of the macro is to create a function that separates the input while also allowing the character to be in it via escaping. Since major changes to the `vertico` module are out of scope here, my suggestion is to change its setting over there to some regexp/function that matches `SPC` or `&` (like it already does), _unless preceded by `\`_. Since Emacs doesn't support negative look-behind, it would need to be a function. This keeps the old behavior of Vertico, just with the new possibility of escaping, applying it to Corfu as well. The caveat here is that I'd rather not make the separator configurable for now, since it is not in Vertico. We can pull-request both modules upstream to fix that later. For comparison, your current implementation uses `,` instead of `&` and is slightly more complicated, but otherwise behaves the same.
2. Some keybindings were not always working (partly my fault, some where buggy before your PR), and you didn't use the `map!` macro for those you added. It simplifies things quite a bit.
3. The extra CAPFs would be better if conditionally applied, for instance behind a module flag (excluding very specific ones, like for elisp and pcomplete). This way the user can choose to their liking. I for one, find that `cape-line` clutters the completion, but like the others.
4. The git history is very big and there are some commits that just undo prior modifications. For the sake of organization, I'll squash them with a more general message describing changes.

I have already implemented 1-3 locally, so no need to change this PR. After you comment back and if there are no urgent issues with what I've described above, I can merge and do 4. Then, if you have other improvements feel free to open other pull requests.

**Comment by LemonBreezes** [comment]
> @LemonBreezes
> 
> I've checked this and it does seem quite good. I have some minor improvements/fixes and one behavior change, but I can add those after merging (I have them ready). Overall:
> 
> 1. The only issue I see is that the `vertico` module already sets `orderless-component-separator` to `"[ &]"`, so the result of `+orderless-escapable-split-fn` may not be used depending on load order. In my `init.el`, `vertico` comes after `corfu`, and therefore breaks the separator (also breaks on `doom/reload`). If I understood correctly, the purpose of the macro is to create a function that separates the input while also allowing the character to be in it via escaping. Since major changes to the `vertico` module are out of scope here, my suggestion is to change its setting over there to some regexp/function that matches `SPC` or `&` (like it already does), _unless preceded by `\`_. Since Emacs doesn't support negative look-behind, it would need to be a function. This keeps the old behavior of Vertico, just with the new possibility of escaping, applying it to Corfu as well. The caveat here is that I'd rather not make the separator configurable for now, since it is not in Vertico. We can pull-request both modules upstream to fix that later. For comparison, your current implementation uses `,` instead of `&` and is slightly more complicated, but otherwise behaves the same.
> 2. Some keybindings were not always working (partly my fault, some where buggy before your PR), and you didn't use the `map!` macro for those you added. It simplifies things quite a bit.
> 3. The extra CAPFs would be better if conditionally applied, for instance behind a module flag (excluding very specific ones, like for elisp and pcomplete). This way the user can choose to their liking. I for one, find that `cape-line` clutters the completion, but like the others.
> 4. The git history is very big and there are some commits that just undo prior modifications. For the sake of organization, I'll squash them with a more general message describing changes.
> 
> I have already implemented 1-3 locally, so no need to change this PR. After you comment back and if there are no urgent issues with what I've described above, I can merge and do 4. Then, if you have other improvements feel free to open other pull requests.

Regarding 1, reference my previous PR here https://github.com/doomemacs/doomemacs/pull/6758. To be honest, I closed it myself because I did not feel the will to defend it then. But since speaking with @pushqrdx and switching from `&` to `,`, I believe in it more strongly. Basically, using `&` as a separator at all is kind of Doom-fu and no one knows why it's there. Since then, no one has complained about the ampersand nor even bothered to change that behavior. So I think it's okay that we change that behavior. It's only useful for Corfu and Company as well, not Vertico itself. Personally, I strongly believe we should be able to customize that character since people conceivably will have different preferences for that. We can make the default `&`. One additional argument we can make is that users of Company have no way to insert a separator like how you can in Corfu.

2. Sure. I did not use `M-j` but I did notice it was broken, so I fixed it.

3. Sure. I was actually thinking of adding `pcmpl-args` and `fish-completion`. One trick I have in my config is:
```elisp
  ;; Enable Fish autocompletion in `read-shell-command'.
  (advice-add #'shell-completion-vars :after #'turn-on-fish-completion-mode)
```

4. Sure. I honestly don't really know how to tidy the commits in Magit.

**Comment by LuigiPiucco** [comment]
> Regarding 1, reference my previous PR here [doomemacs#6758](https://github.com/doomemacs/doomemacs/pull/6758). To be honest, I closed it myself because I did not feel the will to defend it then. But since speaking with @pushqrdx and switching from `&` to `,`, I believe in it more strongly. Basically, using `&` as a separator at all is kind of Doom-fu and no one knows why it's there. Since then, no one has complained about the ampersand nor even bothered to change that behavior. So I think it's okay that we change that behavior. It's only useful for Corfu and Company as well, not Vertico itself. Personally, I strongly believe we should be able to customize that character since people conceivably will have different preferences for that. We can make the default `&`. One additional argument we can make is that users of Company have no way to insert a separator like how you can in Corfu.

From the discussion at https://github.com/doomemacs/doomemacs/pull/6758, I think the following alternative courses of action could work:

* Use escapable `SPC` only as the separator everywhere.
  * Vertico: Bare `SPC` types " " which acts as the separator, `\ SPC` types "\\ " which escapes and includes the `SPC` in the search. No extra bindings required, though can be implemented like below for completeness.
  * Corfu: Bare `SPC` always ends completion and types " ", `C-SPC` calls `corfu-insert-separator` which types " " to act as the separator, `C-SPC` again escapes the " " if point is at one (by typing "\\" before it).
  * Company: Ideally should act the same as above, which may require code intervention to its module. If deemed to complex, we can also leave that be due to missing the required API.
  * Orderless: Can be configured everywhere with a function separator that splits at `SPC` unless preceded by `\` (this may allow extracting duplicated code to its own module.
* Same as prior, but compatible with `&`.
  * Vertico: Same as prior, but `SPC` and `&` are interchangeable.
  * Corfu: Same as prior, but since Orderless will recognize `&` as separator, the user can also type that instead of using `C-SPC`, and `C-SPC` should recognize `&` as escapable as well.
  * Company: Same as above.
  * Orderless: Same as prior, but the regexps are a little more complicated.
* Same as prior (second alternative), but with `,` everywhere instead of `&`.
* Same as second and third, but with a configurable character beside `SPC`, instead of hardcoded.

I think the first is enough, and that the initial addition of Corfu should be limited to that. We can later bring the other options up to check if other people see value in their added complexity. My immediate course of action will be to merge your changes but remove the `,` and unify its behavior into `SPC` for now.

> 4\. Sure. I honestly don't really know how to tidy the commits in Magit.

What helped me the most was looking up how to do a rebase with it. It allows you to modify prior commits if you made a mistake. `r m` with point at a commit is the most important binding. It reverts to that commit, allows you to stage new modifications, then `r r` reapplies all newer commits on top of the modified version, stopping in case of conflict. Another one is `r k`, which removes a commit from the history. Also, I see you force-pushed many times, that's only needed if you modify the history after it's been pushed. If you just add new commits, leaving old ones untouched, regular push works even after you open the PR.

**Pull request merged**
